### ISSUE TITLE
Apply rotation to the map

### ISSUE THREAD

**Issue by androidotai** [stefanocudini/leaflet-compass#14]
Hello team, great works!
One question. How to apply the same rotation to the map, instead of to the compass?

**Comment by stefanocudini** [comment]
no Leaflet don't support map rotation :(

**Comment by Malvoz** [comment]
A bit late of a response, found this issue by accident - which reminded me of the [Raruto/leaflet-rotate](https://github.com/Raruto/leaflet-rotate) plugin.
