### ISSUE TITLE
Does not work on iPhone

### ISSUE THREAD

**Issue by mirabilos** [stefanocudini/leaflet-compass#15]
The demo https://opengeo.tech/maps/leaflet-compass/examples/simple.html matches my own experience in that it always shows 0°

iPhone SE, iOS 15.7.1 (latest as of today); more info on request

**Comment by stefanocudini** [comment]
@mirabilos can you send a PR please?

**Comment by mirabilos** [comment]
Sure; while this in theory “should” not negatively affect others, some extra testing wouldn’t go amiss though.

**Comment by stefanocudini** [comment]
unfortunately I don't have Apple devices available to test, I hope someone can contribute on this

**Comment by mirabilos** [comment]
Stefano Cudini dixit:

>unfortunately I don't have Apple devices available to test, I hope
>someone can contribute on this

It works on an iPhone SE with the latest iOS 15 anyway (these don’t
get iOS 16 but 15 is still kept updated). Someone probably should
test it with 16. But the Android side is the one that needs more
testing, I guess. (As regards the “this doesn’t break anything that
worked before” part, not the functionality.)

bye,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999
