### ISSUE TITLE
Package still maintained?

### ISSUE THREAD

**Issue by dandv** [stefanocudini/leaflet-compass#4]
Could use an update for Meteor 0.9+.

https://atmospherejs.com/mrt/leaflet-compass

**Comment by stefanocudini** [comment]
i @dandv I didn't understood how do it in a clean way.
I had the same problem with leaflet-search

**Comment by stefanocudini** [comment]
hi @dandv  this is updated to new Meteor 1.3
I'll maintain it in the future:
https://atmospherejs.com/stefcud/leaflet-compass
