### ISSUE TITLE
Hi,man!I download this demo，but can't run .

### ISSUE THREAD

**Issue by adustdu2015** [stefanocudini/leaflet-compass#9]
when I import the leaflet.css and leaflet.js,it can't rotate。
![image](https://user-images.githubusercontent.com/17478136/37758533-829d3b92-2deb-11e8-8326-edc5d965f1a1.png)

**Comment by adustdu2015** [comment]
can you think about   leaflet 1.3.1 compatibility? I now use the latest version 1.3.1

**Comment by stefanocudini** [comment]
it work OBVIOUSLY only at mobile device having compass sensor...!!!

alternately
 if you want to test your desktop you can connect an external sensor with arduino
https://www.youtube.com/watch?v=2844oJSRnyU
